export const mockColors = [
  "Trắng",
  "Đen",
  "Nâu",
  "Nâu socola",
  "Vàng kem",
  "Kem",
  "Nâu vàng nhạt",
  "Nâu rám",
  "Xám",
  "Xám xanh",
  "Xanh lam",
  "Đỏ",
  "Cam",
  "Vàng",
  "Vàng mơ",
  "Bạc",
  "Loang sọc",
  "Loang chấm",
  "Đen pha nâu",
  "Tam thể",
  "Vằn mèo",
  "Mai rùa",
  "Hai màu",
  "Ba màu",
  "Nâu đậm",
  "Tím nhạt",
  "Quế",
  "Be",
  "Trắng ngà",
  "Đen trắng kiểu vest",
  "Thân nhạt, mặt đậm",
  "Vằn mặt, tai",
  "Khói",
  "Loang đều",
  "Trắng với mặt và đuôi có màu",
  "Đốm trắng lớn",
  "Nâu tự nhiên",
  "Champagne",
  "Bạch tạng",
  "Chân trắng, mặt màu",
  "Xám than",
  "Nâu gỉ",
  "Nâu gụ",
  "Nâu gan",
  "Hồng đào",
  "Xám tro",
  "Xanh rêu",
  "Trắng tuyết",
  "Đồng đỏ",
  "Xám thép",
  "Hổ phách",
  "Xám rêu",
  "Hồng tro",
  "Bạch kim",
  "Đen tuyền",
];
