export const mockColors = [
  "Trắng",
  "Đen",
  "Nâu",
  "Nâu socola",
  "Vàng kem",
  "Kem",
  "Nâu vàng nhạt",
  "Nâu rám",
  "Xám",
  "Vàng nhạt",
  "Xám xanh",
  "Xanh lam",
  "Đỏ",
  "Cam",
  "Vàng",
  "Vàng mơ",
  "Bạc",
  "Loang sọc",
  "Loang chấm",
  "Đen pha nâu",
  "Tam thể",
  "Vằn mèo",
  "Mai rùa",
  "Hai màu",
  "Ba màu",
  "Nâu đậm",
  "Tím nhạt",
  "Quế",
  "Be",
  "Trắng ngà",
  "Đen trắng kiểu vest",
  "Thân nhạt mặt đậm",
  "Vằn mặt tai",
  "Khói",
  "Loang đều",
  "Trắng với mặt và đuôi có màu",
  "Đốm trắng lớn",
  "Nâu tự nhiên",
  "Champagne",
  "Bạch tạng",
  "Chân trắng mặt màu",
  "Xám than",
  "Nâu gỉ",
  "Nâu gụ",
  "Nâu gan",
  "Hồng đào",
  "Xám tro",
  "Xanh rêu",
  "Trắng tuyết",
  "Đồng đỏ",
  "Xám thép",
  "Hổ phách",
  "Xám rêu",
  "Hồng tro",
  "Bạch kim",
  "Đen tuyền",
  "Vàng cát",
  "Nâu cát",
  "Nâu đỏ",
  "Vàng đỏ",
  "Xám bạc",
  "Trắng pha xám",
  "Trắng pha vàng",
  "Đen pha trắng",
  "Đen pha vàng",
  "Xám tabby",
  "Nâu tabby",
  "Vện nâu đen",
  "Vàng cát",
  "Nâu sable",
  "Loang merle",
  "Loang xám xanh",
  "Loang đỏ nâu",
  "Đốm nhỏ",
  "Ba màu",
  "Hai màu",
  "Trắng toàn thân",
  "Đen toàn thân",
  "Nâu toàn thân",
  "Vàng óng",
  "Bạc ánh kim",
  "Mướp xám",
  "Mướp nâu",
  "Mướp cam",
  "Tam thể",
  "Mai rùa vằn",
  "Đỏ cam",
  "Kem nhạt",
  "Vàng champagne",
  "Nâu quế",
  "Cam nhạt",

];
